"""Static content and progressively enhanced reflection worksheet."""
from html import escape as e


def reflection_content(data):
    topics = ''.join(f'<option value="{t["id"]}">{e(t["label"])}</option>' for t in data['topics'])
    examples = ''.join(f'<details class="reflection-example"><summary>{e(t["label"])}</summary><p>{e(t["description"])}</p><p><strong>Fictional observation:</strong> {e(t["example"]["observation"])}</p></details>' for t in data['topics'])
    cards = ''.join(f'''<article class="reflection-source" data-source-topics="{' '.join(s['topics'])}"><p class="mono-label">{e(s['publisher'])}</p><h3>{e(s['title'])}</h3><p><strong>Date:</strong> {e(s['date'])}</p><p>{e(s['finding'])}</p><details><summary>Who it covers &amp; what it cannot tell us</summary><p><strong>Population / audience:</strong> {e(s['population'])}</p><p><strong>Limit:</strong> {e(s['limit'])}</p></details><p class="source-question">{e(s['prompt'])}</p><a href="{e(s['url'])}" rel="noreferrer">Read the original source</a></article>''' for s in data['sources'])
    def field(id, label, hint='', required=True):
        return f'<div class="form-field"><label for="{id}">{label}</label><textarea id="{id}" name="{id}" rows="3" maxlength="1500"{ " required" if required else ""}{f" aria-describedby={id}-hint" if hint else ""}></textarea>{f"<p class=field-hint id={id}-hint>{hint}</p>" if hint else ""}</div>'
    return f'''<section class="page-hero site-shell reflection-hero"><p class="eyebrow">A Signal &amp; Self activity · about 5 minutes</p><h1>Digital Citizen<br><span class="serif-italic">Reflection</span></h1><p class="page-lede">Turn one online habit into evidence and action. Keep what helps you. Choose one thing to change.</p><a class="button button-primary" href="#reflection-activity">Start your reflection</a><p>No sign-in needed. Your answers stay in this browser.</p></section>
<section class="section site-shell reflection-shell" id="reflection-activity" aria-labelledby="activity-title"><h2 id="activity-title">One habit. Four steps.</h2>
<div class="reflection-storage js-only" hidden><label><input type="checkbox" id="reflection-save"> Save on this device</label><p>When enabled, drafts save automatically in this browser. They do not sync across devices. On a shared device, others using this browser may see them.</p><p id="reflection-storage-status" role="status">Temporary session. Nothing is saved.</p><div id="reflection-resume" hidden><p>A saved reflection is available on this device.</p><button class="button button-primary" type="button" id="reflection-resume-button">Resume saved reflection</button></div><button class="button button-quiet" type="button" id="reflection-clear">Clear reflection</button><p id="reflection-clear-confirm" hidden>Clear your answers and the saved draft? <button class="button button-quiet" id="reflection-clear-yes" type="button">Yes, clear</button> <button class="button button-quiet" id="reflection-clear-no" type="button">Keep reflection</button></p></div>
<p><a href="../assets/downloads/digital-citizen-worksheet.pdf">Download the one-page printable worksheet (PDF)</a></p>
<p class="reflection-nojs">This worksheet works on paper too. With JavaScript disabled, read the sources and print this page to write your answers.</p>
<nav aria-label="Reflection steps" class="reflection-steps js-only" hidden><button type="button" data-reflection-step="0">1 Observe</button><button type="button" data-reflection-step="1">2 Evaluate</button><button type="button" data-reflection-step="2">3 Identify</button><button type="button" data-reflection-step="3">4 Act</button></nav>
<p id="reflection-progress" class="mono-label js-only" role="status" hidden></p>
<form id="reflection-form" autocomplete="off">
<section class="reflection-step" data-step="0" aria-labelledby="observe-title"><h3 id="observe-title" tabindex="-1">1 · Observe a habit</h3><p>Choose a topic, then describe something specific. You can begin with a fictional example.</p><label class="form-field" for="reflection-topic">Topic<select id="reflection-topic" name="topic">{topics}</select></label><div class="button-row js-only" hidden><button type="button" id="reflection-example" class="button button-quiet">Use fictional example</button><button type="button" id="reflection-own" class="button button-quiet">Start my own reflection</button></div><p id="reflection-mode" role="status">Your own reflection · no example loaded</p><div id="reflection-switch-confirm" hidden><p>Starting another topic or example replaces your current answers.</p><button type="button" class="button button-primary" id="reflection-switch-yes">Replace answers</button> <button type="button" class="button button-quiet" id="reflection-switch-no">Keep current answers</button></div>
{field('observation','What do you do online?','Describe one habit; avoid names or private details.')}{field('context','When or where does it happen?')}{field('notice','What do you notice afterward?','Consider benefits as well as things that get in the way.')}
<div id="attention-comparison"><h4>Time comparison · optional</h4><div class="reflection-time"><label for="before">Current minutes per day<input id="before" name="before" type="number" min="0" max="1440" step="1" inputmode="numeric"></label><label for="after">Planned minutes per day<input id="after" name="after" type="number" min="0" max="1440" step="1" inputmode="numeric"></label></div><p id="reflection-arithmetic" role="status">Enter both values to compare them. These are arithmetic estimates, not health recommendations.</p><div class="reflection-bars" aria-hidden="true"><span id="before-bar"></span><span id="after-bar"></span></div></div></section>
<section class="reflection-step" data-step="1" aria-labelledby="evaluate-title"><h3 id="evaluate-title" tabindex="-1">2 · Evaluate the evidence</h3><p>Read the evidence relevant to your topic. Compare a finding with its limits: a source can be credible without answering every question.</p><div class="reflection-sources">{cards}</div>{field('evidenceResponse','What does the evidence help you understand?','What can it support, and what would you still need to check about your own situation?')}</section>
<section class="reflection-step" data-step="2" aria-labelledby="identify-title"><h3 id="identify-title" tabindex="-1">3 · Identify a risk</h3><label class="form-field" for="risk">What risk do you want to address?<select id="risk" name="risk"><option value="">Choose a risk</option><option value="other">Describe my own risk</option></select></label>{field('riskDetail','Describe the risk (optional)','Use this to add context or describe your own risk.',False)}{field('benefit','What benefit do you want to keep?','A change can preserve connection, creativity, learning, or another benefit you value.')}</section>
<section class="reflection-step" data-step="3" aria-labelledby="act-title"><h3 id="act-title" tabindex="-1">4 · Choose a realistic change</h3>{field('change','What is one change you will try?','Make it small enough to try in your real routine.')}{field('check','How will you check what happens?','Choose an observable check, such as whether you found the original source before sharing.')}<label class="form-field" for="reviewDate">When will you review it?<input type="date" id="reviewDate" name="reviewDate" required></label><button type="button" class="button button-primary js-only" id="reflection-finish" hidden>Build my action plan</button></section>
<div class="reflection-navigation js-only" hidden><button type="button" id="reflection-back" class="button button-quiet">Back</button><button type="button" id="reflection-next" class="button button-primary">Next step</button></div></form>
<section id="reflection-summary" hidden aria-labelledby="summary-title"><h3 id="summary-title" tabindex="-1">Your action plan</h3><p id="summary-mode"></p><dl id="summary-content"></dl><div class="button-row"><button type="button" class="button button-quiet" id="reflection-edit">Edit my answers</button><button type="button" class="button button-primary" id="reflection-download">Download text</button><button type="button" class="button button-quiet" id="reflection-print">Print action plan</button></div><p>Keep the benefit. Try the change. Review what actually happened.</p></section></section>
<section class="section site-shell reflection-examples" aria-labelledby="examples-title"><h2 id="examples-title">Four ways to begin</h2><p>All examples are fictional. None describes Mina's habits or a measured outcome.</p>{examples}</section>
<script type="application/json" id="reflection-data">{__import__('json').dumps(data,ensure_ascii=False).replace('<',chr(92)+'u003c')}</script>'''
